### ISSUE TITLE
Crash - Client Side

### ISSUE THREAD

**Issue by DPxKnightxZero** [LothrazarMinecraftMods/OverpoweredInventory#4]
1.7.10 Latest

Crash Log -> https://gist.github.com/DPxKnightxZero/e81db74fa25d4183b87a

Full Log -> https://gist.github.com/DPxKnightxZero/b171acc75c6458f7303c

**Comment by PrinceOfAmber** [comment]
Thanks for the report.  Sorry ive been ignoring the issue tracker on github.  Current version is for Minecraft 1.10.2, and this issue doesnt happen there. please report it if you see it again
