### ISSUE TITLE
OPInventory resets when using exit end portal

### ISSUE THREAD

**Issue by Codemonkey6658** [LothrazarMinecraftMods/OverpoweredInventory#5]
when you enter the end it still keeps your inventory but when you use the exit end portal and get the credits it resets it 

Using version 2.1.0 for minecraft 1.8.9

**Comment by PrinceOfAmber** [comment]
Sorry for taking so long to respond.  Ill test this out in the latest version.

**Comment by PrinceOfAmber** [comment]
Should be fixed in new version, let me know how it goes! 

https://minecraft.curseforge.com/projects/overpowered-inventory-375-inventory-slots-and-more/files/2323143
